.Dd May 11, 2018
.Dt TRUEOS-UPDATE 8
.Os TrueOS
.\"----------------------------------------------------------------
.Sh NAME
.Nm trueos-update
.Nd System update utility for TrueOS.
.\"----------------------------------------------------------------
.Sh SYNOPSIS
.Nm
.Op <command> <args>
.\"----------------------------------------------------------------
.Sh DESCRIPTION
The
.Nm
utility finds and installs updates to TrueOS.
.Pp
.\" Here are the options:
The check / fetch commands automatically boot-strap the updater to its latest verion.
.Pp
Here are the available commands:
.Bl -tag -width indent
.It Ic check
Checks for updates, will return if packages have updates available.
.It Ic upgrade Ar -f
Starts a system upgrade. Packages will be downloaded, the system rebooted and
then upgraded. If the
.Fl f
flag is pointing to an upgrade tarball, it will be used instead of fetching
the packages from the update server. WARNING: This will reboot your
system as part of the update process.
.\"----------------------------------------------------------------
.Sh EXAMPLES
.Bl -tag -width indent
.It trueos-update upgrade
Start an update on the system.
.\"----------------------------------------------------------------
.Sh SEE ALSO
.Xr beadm(1),
.Xr pkg(8)
.\"----------------------------------------------------------------
.Sh AUTHORS
.An Tim Moore
.Aq timmoore88@gmail.com
